import type { Project, About } from './types'

export const DUMMY_PROJECTS: Project[] = [
  {
    id: '1', slug: 'echo', title: 'Echo',
    subtitleType: 'None', subtitleName: 'A Study in Sound and Space',
    type: ['Film'], date: 'March 2024',
    thumbnail: { url: 'https://picsum.photos/seed/echo/620/440', alt: 'Echo', width: 620, height: 440 },
    thumbnails: [
      { url: 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4', alt: 'Echo film', type: 'video' as const },
    ],
    photos: [
      { _key: 'e1', url: 'https://picsum.photos/seed/echo1/1200/800', alt: 'Still 1' },
      { _key: 'e2', url: 'https://picsum.photos/seed/echo2/1200/800', alt: 'Still 2' },
    ],
    videos: [{ _type: 'linkedVideo', _key: 'ev1', url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', caption: 'Full film' }],
    audio: [], description: 'A short film exploring sound and space in urban environments. Shot on 16mm over three nights in lower Manhattan.', links: [{ label: 'Vimeo', url: 'https://vimeo.com' }],
    roles: ['Composition', 'Sound Design', 'Mixing', 'Mastering'],
    collaborators: [
      { name: 'Maya Lin', url: 'https://mayalin.com' },
      { name: 'Ryuichi Sakamoto' },
    ],
    presentedAt: [
      { name: 'Tribeca Film Festival', url: 'https://tribecafilm.com' },
      { name: 'AFI Fest' },
    ],
    watchOn: [
      { name: 'Vimeo', url: 'https://vimeo.com' },
    ],
    press: [
      { name: 'Filmmaker Magazine', url: 'https://filmmakermagazine.com' },
      { name: 'Sight & Sound' },
    ],
    order: 1,
  },
  {
    id: '2', slug: 'dissolve', title: 'Dissolve',
    subtitleType: 'None', subtitleName: 'After the Image', subtitleUrl: 'https://criterionchannel.com',
    type: ['Film', 'Releases'], date: 'November 2023',
    thumbnail: { url: 'https://picsum.photos/seed/dissolve/620/440', alt: 'Dissolve', width: 620, height: 440 },
    thumbnails: [
      { url: 'https://picsum.photos/seed/dissolve/620/440', alt: 'Dissolve 1' },
      { url: 'https://picsum.photos/seed/dissolve-b/620/440', alt: 'Dissolve 2' },
      { url: 'https://picsum.photos/seed/dis1/620/440', alt: 'Dissolve 3' },
      { url: 'https://picsum.photos/seed/dis2/620/440', alt: 'Dissolve 4' },
    ],
    photos: [
      { _key: 'd1', url: 'https://picsum.photos/seed/dis1/900/1200', alt: 'Frame 1' },
      { _key: 'd2', url: 'https://picsum.photos/seed/dis2/1200/800', alt: 'Frame 2' },
    ],
    videos: [{ _type: 'linkedVideo', _key: 'dv1', url: 'https://vimeo.com/148751763', caption: 'Trailer' }],
    audio: [
      { _key: 'da1', fileUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3', caption: 'Original score — "Dissolve Theme"' },
      { _key: 'da2', fileUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3', caption: 'Ambient texture, act II' },
    ],
    description: 'Documentary short about obsolete film formats and the communities that preserve them.', links: [],
    roles: ['Production', 'Recording', 'Mixing'],
    collaborators: [
      { name: 'Werner Herzog', url: 'https://wernerherzog.com' },
      { name: 'Ennio Morricone' },
    ],
    watchOn: [
      { name: 'Criterion Channel', url: 'https://criterionchannel.com' },
    ],
    press: [
      { name: 'The Wire', url: 'https://thewire.co.uk' },
    ],
    order: 2,
  },
  {
    id: '3', slug: 'grain', title: 'Grain',
    subtitleType: 'For', subtitleName: 'A24 Labs', subtitleUrl: 'https://a24films.com',
    type: ['Film', 'Art'], date: 'July 2024',
    thumbnail: { url: 'https://picsum.photos/seed/grain/620/440', alt: 'Grain', width: 620, height: 440 },
    thumbnails: [
      { url: 'https://picsum.photos/seed/grain/620/440', alt: 'Grain 1' },
      { url: 'https://picsum.photos/seed/grain-b/620/440', alt: 'Grain 2' },
      { url: 'https://picsum.photos/seed/gr1/620/440', alt: 'Grain 3' },
    ],
    photos: [
      { _key: 'g1', url: 'https://picsum.photos/seed/gr1/1200/800', alt: 'Still 1' },
      { _key: 'g2', url: 'https://picsum.photos/seed/gr2/1200/900', alt: 'Still 2' },
    ],
    videos: [{ _type: 'linkedVideo', _key: 'gv1', url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', caption: 'Full piece' }],
    audio: [], description: 'An experimental piece about texture, memory, and the physical artifact of cinema.', links: [{ label: 'A24', url: 'https://a24films.com' }],
    roles: ['Sound Installation', 'Composition', 'Audiovisual Direction'],
    collaborators: [
      { name: 'Hito Steyerl', url: 'https://e-flux.com' },
      { name: 'Björk', url: 'https://bjork.com' },
      { name: 'Scanner' },
    ],
    presentedAt: [
      { name: 'Berlinale', url: 'https://berlinale.de' },
    ],
    press: [
      { name: 'Artforum', url: 'https://artforum.com' },
      { name: 'frieze', url: 'https://frieze.com' },
      { name: 'Mousse Magazine' },
    ],
    order: 3,
  },
  {
    id: '4', slug: 'ss-campaign', title: 'S/S Campaign',
    subtitleType: 'For', subtitleName: 'Acne Studios', subtitleUrl: 'https://acnestudios.com',
    type: ['Fashion', 'Campaign'], date: 'January 2024',
    thumbnail: { url: 'https://picsum.photos/seed/acne/620/440', alt: 'S/S Campaign', width: 620, height: 440 },
    thumbnails: [
      { url: 'https://picsum.photos/seed/acne/620/440', alt: 'S/S 1' },
      { url: 'https://picsum.photos/seed/acne-b/620/440', alt: 'S/S 2' },
      { url: 'https://picsum.photos/seed/acne1/620/440', alt: 'S/S 3' },
      { url: 'https://picsum.photos/seed/acne2/620/440', alt: 'S/S 4' },
    ],
    photos: [
      { _key: 'a1', url: 'https://picsum.photos/seed/acne1/900/1200', alt: 'Look 1' },
      { _key: 'a2', url: 'https://picsum.photos/seed/acne2/900/1200', alt: 'Look 2' },
    ],
    videos: [{ _type: 'linkedVideo', _key: 'av1', url: 'https://vimeo.com/148751763', caption: 'Campaign film' }],
    audio: [], description: 'Spring/Summer 2024 campaign for Acne Studios. Photographed in rural Iceland over five days.', links: [{ label: 'Acne Studios', url: 'https://acnestudios.com' }],
    roles: ['Music Supervision', 'Music Direction'],
    watchOn: [
      { name: 'YouTube', url: 'https://youtube.com' },
      { name: 'Acne Studios', url: 'https://acnestudios.com' },
    ],
    press: [
      { name: 'Vogue', url: 'https://vogue.com' },
      { name: 'i-D', url: 'https://i-d.vice.com' },
    ],
    order: 4,
  },
  {
    id: '5', slug: 'lookbook-iii', title: 'Lookbook III',
    subtitleType: 'For', subtitleName: 'Paloma Wool',
    type: ['Fashion'], date: 'September 2023',
    thumbnail: { url: 'https://picsum.photos/seed/paloma/620/440', alt: 'Lookbook III', width: 620, height: 440 },
    thumbnails: [
      { url: 'https://picsum.photos/seed/paloma/620/440', alt: 'LB 1' },
      { url: 'https://picsum.photos/seed/paloma-b/620/440', alt: 'LB 2' },
      { url: 'https://picsum.photos/seed/pw1/620/440', alt: 'LB 3' },
    ],
    photos: [
      { _key: 'pw1', url: 'https://picsum.photos/seed/pw1/1200/800', alt: 'Look 1' },
      { _key: 'pw2', url: 'https://picsum.photos/seed/pw2/900/1200', alt: 'Look 2' },
    ],
    videos: [], audio: [], description: 'Third seasonal lookbook for Paloma Wool.', links: [], order: 5,
  },
  {
    id: '6', slug: 'after-hours', title: 'After Hours',
    subtitleType: 'For', subtitleName: 'Bottega Veneta',
    type: ['Fashion'], date: 'April 2024',
    thumbnail: { url: 'https://picsum.photos/seed/bottega/620/440', alt: 'After Hours', width: 620, height: 440 },
    thumbnails: [
      { url: 'https://picsum.photos/seed/bottega/620/440', alt: 'AH 1' },
      { url: 'https://picsum.photos/seed/bottega-b/620/440', alt: 'AH 2' },
      { url: 'https://picsum.photos/seed/bv1/620/440', alt: 'AH 3' },
      { url: 'https://picsum.photos/seed/bv2/620/440', alt: 'AH 4' },
    ],
    photos: [
      { _key: 'bv1', url: 'https://picsum.photos/seed/bv1/900/1200', alt: 'Image 1' },
      { _key: 'bv2', url: 'https://picsum.photos/seed/bv2/1200/800', alt: 'Image 2' },
    ],
    videos: [{ _type: 'linkedVideo', _key: 'bvid1', url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', caption: 'Film' }],
    audio: [], description: "Editorial for Bottega Veneta's evening collection. Shot in a decommissioned power plant.", links: [],
    watchOn: [
      { name: 'Bottega Veneta', url: 'https://bottegaveneta.com' },
    ],
    press: [
      { name: 'Another Magazine', url: 'https://anothermag.com' },
    ],
    order: 6,
  },
  {
    id: '7', slug: 'negative-space', title: 'Negative Space',
    subtitleType: 'For', subtitleName: 'Pace Gallery', subtitleUrl: 'https://pacegallery.com',
    type: ['Art', 'Performance'], date: 'June 2023',
    thumbnail: { url: 'https://picsum.photos/seed/negspace/620/440', alt: 'Negative Space', width: 620, height: 440 },
    thumbnails: [
      { url: 'https://picsum.photos/seed/negspace/620/440', alt: 'NS 1' },
      { url: 'https://picsum.photos/seed/negspace-b/620/440', alt: 'NS 2' },
      { url: 'https://picsum.photos/seed/ns1/620/440', alt: 'NS 3' },
    ],
    photos: [
      { _key: 'ns1', url: 'https://picsum.photos/seed/ns1/1200/1200', alt: 'Work 1' },
      { _key: 'ns2', url: 'https://picsum.photos/seed/ns2/1200/800', alt: 'Installation view' },
    ],
    videos: [], audio: [], description: 'Documentation of a site-specific installation at Pace Gallery, New York.', links: [{ label: 'Pace Gallery', url: 'https://pacegallery.com' }],
    roles: ['Sound Installation', 'Conducting', 'Performance'],
    presentedAt: [
      { name: 'Pace Gallery, New York', url: 'https://pacegallery.com' },
      { name: 'Haus der Kunst, Munich', url: 'https://hausderkunst.de' },
    ],
    press: [
      { name: 'The New York Times', url: 'https://nytimes.com' },
    ],
    order: 7,
  },
  {
    id: '8', slug: 'surface-tension', title: 'Surface Tension',
    subtitleType: 'By', subtitleName: 'Self-initiated',
    type: ['Art', 'Releases'], date: 'February 2024',
    thumbnail: { url: 'https://picsum.photos/seed/surface/620/440', alt: 'Surface Tension', width: 620, height: 440 },
    thumbnails: [
      { url: 'https://picsum.photos/seed/surface/620/440', alt: 'ST 1' },
      { url: 'https://picsum.photos/seed/surface-b/620/440', alt: 'ST 2' },
      { url: 'https://picsum.photos/seed/st1/620/440', alt: 'ST 3' },
      { url: 'https://picsum.photos/seed/st2/620/440', alt: 'ST 4' },
    ],
    photos: [
      { _key: 'st1', url: 'https://picsum.photos/seed/st1/1200/800', alt: 'Detail 1' },
      { _key: 'st2', url: 'https://picsum.photos/seed/st2/1200/800', alt: 'Detail 2' },
    ],
    videos: [{ _type: 'linkedVideo', _key: 'stv1', url: 'https://vimeo.com/148751763', caption: 'Process film' }],
    audio: [
      { _key: 'sta1', fileUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3', caption: 'Field recording — studio session' },
    ],
    description: 'A series of photographic works examining materiality and surface at macro scale.', links: [],
    roles: ['Recording', 'Sound Design', 'Mastering'], order: 8,
  },
  {
    id: '9', slug: 'archive', title: 'Archive',
    subtitleType: 'For', subtitleName: 'MoMA PS1', subtitleUrl: 'https://momaps1.org',
    type: ['Art'], date: 'October 2023',
    thumbnail: { url: 'https://picsum.photos/seed/archive/620/440', alt: 'Archive', width: 620, height: 440 },
    thumbnails: [
      { url: 'https://picsum.photos/seed/archive/620/440', alt: 'Archive 1' },
      { url: 'https://picsum.photos/seed/archive-b/620/440', alt: 'Archive 2' },
      { url: 'https://picsum.photos/seed/ar1/620/440', alt: 'Archive 3' },
    ],
    photos: [
      { _key: 'ar1', url: 'https://picsum.photos/seed/ar1/900/1200', alt: 'Archive 1' },
      { _key: 'ar2', url: 'https://picsum.photos/seed/ar2/1200/800', alt: 'Archive 2' },
    ],
    videos: [], audio: [], description: 'Exhibition documentation for Archive, a group show at MoMA PS1 surveying found photography.', links: [{ label: 'MoMA PS1', url: 'https://momaps1.org' }], order: 9,
  },
  {
    id: '10', slug: 'identity-refresh', title: 'Identity Refresh',
    subtitleType: 'For', subtitleName: 'The Standard, Devonté Hynes',
    type: ['Campaign', 'Film'], date: 'December 2023',
    thumbnail: { url: 'https://picsum.photos/seed/standard/620/440', alt: 'Identity Refresh', width: 620, height: 440 },
    thumbnails: [
      { url: 'https://picsum.photos/seed/standard/620/440', alt: 'IR 1' },
      { url: 'https://picsum.photos/seed/standard-b/620/440', alt: 'IR 2' },
      { url: 'https://picsum.photos/seed/ir1/620/440', alt: 'IR 3' },
      { url: 'https://picsum.photos/seed/ir2/620/440', alt: 'IR 4' },
    ],
    photos: [
      { _key: 'ir1', url: 'https://picsum.photos/seed/ir1/1200/800', alt: 'Brand identity 1' },
      { _key: 'ir2', url: 'https://picsum.photos/seed/ir2/800/1200', alt: 'Collateral' },
    ],
    videos: [{ _type: 'linkedVideo', _key: 'irv1', url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', caption: 'Brand film' }],
    audio: [], description: 'Visual identity refresh for The Standard Hotels. New typographic system and brand motion language.', links: [{ label: 'The Standard', url: 'https://standardhotels.com' }],
    roles: ['Music Direction', 'Music Programming', 'Arrangement'],
    collaborators: [
      { name: 'Devonté Hynes', url: 'https://bloodorangemusic.com' },
      { name: 'Kelsey Lu', url: 'https://kelseylu.com' },
      { name: 'Caroline Polachek' },
    ], order: 10,
  },
  {
    id: '11', slug: 'campaign-2024', title: 'Campaign 2024',
    subtitleType: 'For', subtitleName: 'New Balance', subtitleUrl: 'https://newbalance.com',
    type: ['Campaign'], date: 'May 2024',
    thumbnail: { url: 'https://picsum.photos/seed/nb2024/620/440', alt: 'Campaign 2024', width: 620, height: 440 },
    thumbnails: [
      { url: 'https://picsum.photos/seed/nb2024/620/440', alt: 'NB 1' },
      { url: 'https://picsum.photos/seed/nb2024-b/620/440', alt: 'NB 2' },
      { url: 'https://picsum.photos/seed/nb1/620/440', alt: 'NB 3' },
    ],
    photos: [
      { _key: 'nb1', url: 'https://picsum.photos/seed/nb1/1200/800', alt: 'Campaign 1' },
      { _key: 'nb2', url: 'https://picsum.photos/seed/nb2/1200/800', alt: 'Campaign 2' },
    ],
    videos: [{ _type: 'linkedVideo', _key: 'nbv1', url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', caption: 'Hero film' }],
    audio: [], description: 'Global campaign for New Balance 2024. Concept, direction, and production.', links: [], order: 11,
  },
  {
    id: '12', slug: 'ritual', title: 'Ritual',
    subtitleType: 'For', subtitleName: 'BAM', subtitleUrl: 'https://bam.org',
    type: ['Performance'], date: 'July 2023',
    thumbnail: { url: 'https://picsum.photos/seed/ritual/620/440', alt: 'Ritual', width: 620, height: 440 },
    thumbnails: [
      { url: 'https://picsum.photos/seed/ritual/620/440', alt: 'Ritual 1' },
      { url: 'https://picsum.photos/seed/ritual-b/620/440', alt: 'Ritual 2' },
      { url: 'https://picsum.photos/seed/r1/620/440', alt: 'Ritual 3' },
      { url: 'https://picsum.photos/seed/r2/620/440', alt: 'Ritual 4' },
    ],
    photos: [
      { _key: 'r1', url: 'https://picsum.photos/seed/r1/1200/800', alt: 'Performance 1' },
      { _key: 'r2', url: 'https://picsum.photos/seed/r2/800/1200', alt: 'Backstage' },
    ],
    videos: [{ _type: 'linkedVideo', _key: 'rv1', url: 'https://vimeo.com/148751763', caption: 'Full performance' }],
    audio: [], description: 'Documentation of Ritual, a durational performance work by Okwui Okpokwasili at BAM.', links: [{ label: 'BAM', url: 'https://bam.org' }],
    roles: ['Composition', 'Orchestration', 'Conducting', 'Arrangement'],
    collaborators: [
      { name: 'Okwui Okpokwasili', url: 'https://okwuiokpokwasili.com' },
    ],
    presentedAt: [
      { name: 'BAM Harvey Theater', url: 'https://bam.org' },
    ],
    watchOn: [
      { name: 'BAM Digital Archive', url: 'https://bam.org' },
    ],
    order: 12,
  },
  {
    id: '13', slug: 'dusk-score', title: 'Dusk Score',
    subtitleType: 'For', subtitleName: 'Lincoln Center', subtitleUrl: 'https://lincolncenter.org',
    type: ['Performance'], date: 'June 2024',
    thumbnail: { url: 'https://picsum.photos/seed/dusk/620/440', alt: 'Dusk Score', width: 620, height: 440 },
    thumbnails: [
      { url: 'https://picsum.photos/seed/dusk/620/440', alt: 'DS 1' },
      { url: 'https://picsum.photos/seed/dusk-b/620/440', alt: 'DS 2' },
      { url: 'https://picsum.photos/seed/ds1/620/440', alt: 'DS 3' },
    ],
    photos: [
      { _key: 'ds1', url: 'https://picsum.photos/seed/ds1/900/1200', alt: 'Image 1' },
      { _key: 'ds2', url: 'https://picsum.photos/seed/ds2/1200/800', alt: 'Image 2' },
    ],
    videos: [{ _type: 'linkedVideo', _key: 'dsv1', url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', caption: 'Excerpt' }],
    audio: [], description: 'Documentation of Dusk Score, an outdoor performance at Lincoln Center Out of Doors.', links: [{ label: 'Lincoln Center', url: 'https://lincolncenter.org' }], order: 13,
  },
  {
    id: '14', slug: 'launch-film', title: 'Launch Film',
    subtitleType: 'For', subtitleName: 'Glossier', subtitleUrl: 'https://glossier.com',
    type: ['Campaign'], date: 'August 2023',
    thumbnail: { url: 'https://picsum.photos/seed/glossier/620/440', alt: 'Launch Film', width: 620, height: 440 },
    thumbnails: [
      { url: 'https://picsum.photos/seed/glossier/620/440', alt: 'LF 1' },
      { url: 'https://picsum.photos/seed/glossier-b/620/440', alt: 'LF 2' },
      { url: 'https://picsum.photos/seed/lf1/620/440', alt: 'LF 3' },
      { url: 'https://picsum.photos/seed/lf2/620/440', alt: 'LF 4' },
    ],
    photos: [
      { _key: 'lf1', url: 'https://picsum.photos/seed/lf1/1200/800', alt: 'Frame 1' },
      { _key: 'lf2', url: 'https://picsum.photos/seed/lf2/1200/800', alt: 'Frame 2' },
    ],
    videos: [{ _type: 'linkedVideo', _key: 'lfv1', url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', caption: 'Full film' }],
    audio: [], description: "Product launch film for Glossier's You fragrance.", links: [{ label: 'Glossier', url: 'https://glossier.com' }], order: 14,
  },
  {
    id: '15', slug: 'still-life', title: 'Still Life',
    subtitleType: 'By', subtitleName: 'Self-initiated',
    type: ['Art'], date: 'January 2024',
    thumbnail: { url: 'https://picsum.photos/seed/stilllife/620/440', alt: 'Still Life', width: 620, height: 440 },
    thumbnails: [
      { url: 'https://picsum.photos/seed/stilllife/620/440', alt: 'SL 1' },
      { url: 'https://picsum.photos/seed/stilllife-b/620/440', alt: 'SL 2' },
      { url: 'https://picsum.photos/seed/sl1/620/440', alt: 'SL 3' },
    ],
    photos: [{ _key: 'sl1', url: 'https://picsum.photos/seed/sl1/1200/800', alt: 'Still 1' }],
    videos: [], audio: [], description: 'A series of large-format photographs.', links: [], order: 15,
  },
  {
    id: '16', slug: 'motion-study', title: 'Motion Study',
    subtitleType: 'For', subtitleName: 'Nike, Arthur Jafa', subtitleUrl: 'https://nike.com',
    type: ['Campaign', 'Fashion'], date: 'March 2024',
    thumbnail: { url: 'https://picsum.photos/seed/nike/620/440', alt: 'Motion Study', width: 620, height: 440 },
    thumbnails: [
      { url: 'https://picsum.photos/seed/nike/620/440', alt: 'MS 1' },
      { url: 'https://picsum.photos/seed/nike-b/620/440', alt: 'MS 2' },
      { url: 'https://picsum.photos/seed/ms1/620/440', alt: 'MS 3' },
      { url: 'https://picsum.photos/seed/ms2/620/440', alt: 'MS 4' },
    ],
    photos: [{ _key: 'ms1', url: 'https://picsum.photos/seed/ms1/1200/800', alt: 'Frame 1' }],
    videos: [{ _type: 'linkedVideo', _key: 'msv1', url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', caption: 'Full film' }],
    audio: [], description: 'Brand film for Nike exploring athletes in motion.', links: [],
    roles: ['Music Supervision', 'Music Editing', 'Mixing', 'Mastering'],
    collaborators: [
      { name: 'Arthur Jafa', url: 'https://hausderkunst.de' },
    ],
    watchOn: [
      { name: 'Nike.com', url: 'https://nike.com' },
      { name: 'YouTube', url: 'https://youtube.com' },
    ],
    press: [
      { name: 'Hypebeast', url: 'https://hypebeast.com' },
      { name: 'Highsnobiety', url: 'https://highsnobiety.com' },
      { name: "It's Nice That", url: 'https://itsnicethat.com' },
    ],
    order: 16,
  },
  {
    id: '17', slug: 'dusk-land', title: 'Dusk Land',
    subtitleType: 'For', subtitleName: 'ICA Boston',
    type: ['Art'], date: 'April 2023',
    thumbnail: { url: 'https://picsum.photos/seed/duskland/620/440', alt: 'Dusk Land', width: 620, height: 440 },
    thumbnails: [
      { url: 'https://picsum.photos/seed/duskland/620/440', alt: 'DL 1' },
      { url: 'https://picsum.photos/seed/duskland-b/620/440', alt: 'DL 2' },
      { url: 'https://picsum.photos/seed/dl1/620/440', alt: 'DL 3' },
    ],
    photos: [{ _key: 'dl1', url: 'https://picsum.photos/seed/dl1/1200/800', alt: 'Work 1' }],
    videos: [], audio: [], description: 'Landscape photography and text for a group exhibition at ICA Boston.', links: [], order: 17,
  },
  {
    id: '18', slug: 'overture', title: 'Overture',
    subtitleType: 'By', subtitleName: 'Self-initiated',
    type: ['Film', 'Releases'], date: 'February 2023',
    thumbnail: { url: 'https://picsum.photos/seed/overture/620/440', alt: 'Overture', width: 620, height: 440 },
    thumbnails: [
      { url: 'https://picsum.photos/seed/overture/620/440', alt: 'Ov 1' },
      { url: 'https://picsum.photos/seed/overture-b/620/440', alt: 'Ov 2' },
      { url: 'https://picsum.photos/seed/ov1/620/440', alt: 'Ov 3' },
      { url: 'https://picsum.photos/seed/ov2/620/440', alt: 'Ov 4' },
    ],
    photos: [{ _key: 'ov1', url: 'https://picsum.photos/seed/ov1/1200/800', alt: 'Still 1' }],
    videos: [{ _type: 'linkedVideo', _key: 'ovv1', url: 'https://vimeo.com/148751763', caption: 'Full film' }],
    audio: [], description: 'Short experimental film made in collaboration with a composer.', links: [],
    roles: ['Songwriting', 'Lyrics', 'Vocal Production', 'Production'], order: 18,
  },
  {
    id: '19', slug: 'collection-i', title: 'Collection I',
    subtitleType: 'For', subtitleName: 'Lemaire',
    type: ['Fashion'], date: 'February 2024',
    thumbnail: { url: 'https://picsum.photos/seed/lemaire/620/440', alt: 'Collection I', width: 620, height: 440 },
    thumbnails: [
      { url: 'https://picsum.photos/seed/lemaire/620/440', alt: 'CI 1' },
      { url: 'https://picsum.photos/seed/lemaire-b/620/440', alt: 'CI 2' },
      { url: 'https://picsum.photos/seed/lm1/620/440', alt: 'CI 3' },
    ],
    photos: [{ _key: 'lm1', url: 'https://picsum.photos/seed/lm1/900/1200', alt: 'Look 1' }],
    videos: [], audio: [], description: 'Collection photography for Lemaire AW24.', links: [], order: 19,
  },
  {
    id: '20', slug: 'interval', title: 'Interval',
    subtitleType: 'For', subtitleName: 'The Kitchen',
    type: ['Performance'], date: 'May 2023',
    thumbnail: { url: 'https://picsum.photos/seed/interval/620/440', alt: 'Interval', width: 620, height: 440 },
    thumbnails: [
      { url: 'https://picsum.photos/seed/interval/620/440', alt: 'Iv 1' },
      { url: 'https://picsum.photos/seed/interval-b/620/440', alt: 'Iv 2' },
      { url: 'https://picsum.photos/seed/iv1/620/440', alt: 'Iv 3' },
      { url: 'https://picsum.photos/seed/iv2/620/440', alt: 'Iv 4' },
    ],
    photos: [{ _key: 'iv1', url: 'https://picsum.photos/seed/iv1/1200/800', alt: 'Performance 1' }],
    videos: [{ _type: 'linkedVideo', _key: 'ivv1', url: 'https://vimeo.com/148751763', caption: 'Documentation' }],
    audio: [], description: 'Performance documentation at The Kitchen, New York.', links: [], order: 20,
  },
  {
    id: '21', slug: 'terrain', title: 'Terrain',
    subtitleType: 'By', subtitleName: 'Self-initiated',
    type: ['Film'], date: 'November 2022',
    thumbnail: { url: 'https://picsum.photos/seed/terrain/620/440', alt: 'Terrain', width: 620, height: 440 },
    thumbnails: [
      { url: 'https://picsum.photos/seed/terrain/620/440', alt: 'Tr 1' },
      { url: 'https://picsum.photos/seed/terrain-b/620/440', alt: 'Tr 2' },
      { url: 'https://picsum.photos/seed/tr1/620/440', alt: 'Tr 3' },
    ],
    photos: [{ _key: 'tr1', url: 'https://picsum.photos/seed/tr1/1200/800', alt: 'Still 1' }],
    videos: [{ _type: 'linkedVideo', _key: 'trv1', url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', caption: 'Full film' }],
    audio: [], description: 'A film about place and displacement.', links: [], order: 21,
  },
  {
    id: '22', slug: 'form-study', title: 'Form Study',
    subtitleType: 'For', subtitleName: 'Haas Brothers',
    type: ['Campaign'], date: 'March 2023',
    thumbnail: { url: 'https://picsum.photos/seed/formstdy/620/440', alt: 'Form Study', width: 620, height: 440 },
    thumbnails: [
      { url: 'https://picsum.photos/seed/formstdy/620/440', alt: 'FS 1' },
      { url: 'https://picsum.photos/seed/formstdy-b/620/440', alt: 'FS 2' },
      { url: 'https://picsum.photos/seed/fs1/620/440', alt: 'FS 3' },
      { url: 'https://picsum.photos/seed/fs2/620/440', alt: 'FS 4' },
    ],
    photos: [{ _key: 'fs1', url: 'https://picsum.photos/seed/fs1/1200/800', alt: 'Object 1' }],
    videos: [], audio: [], description: 'Product and editorial photography for Haas Brothers.', links: [], order: 22,
  },
  {
    id: '23', slug: 'spring', title: 'Spring',
    subtitleType: 'By', subtitleName: 'Self-initiated',
    type: ['Fashion'], date: 'April 2024',
    thumbnail: { url: 'https://picsum.photos/seed/spring/620/440', alt: 'Spring', width: 620, height: 440 },
    thumbnails: [
      { url: 'https://picsum.photos/seed/spring/620/440', alt: 'Sp 1' },
      { url: 'https://picsum.photos/seed/spring-b/620/440', alt: 'Sp 2' },
      { url: 'https://picsum.photos/seed/sp1/620/440', alt: 'Sp 3' },
    ],
    photos: [{ _key: 'sp1', url: 'https://picsum.photos/seed/sp1/1200/800', alt: 'Image 1' }],
    videos: [], audio: [], description: 'Personal project on seasonal change and fashion.', links: [], order: 23,
  },
  {
    id: '24', slug: 'monument', title: 'Monument',
    subtitleType: 'For', subtitleName: 'Public Art Fund',
    type: ['Art'], date: 'August 2023',
    thumbnail: { url: 'https://picsum.photos/seed/monument/620/440', alt: 'Monument', width: 620, height: 440 },
    thumbnails: [
      { url: 'https://picsum.photos/seed/monument/620/440', alt: 'Mn 1' },
      { url: 'https://picsum.photos/seed/monument-b/620/440', alt: 'Mn 2' },
      { url: 'https://picsum.photos/seed/mn1/620/440', alt: 'Mn 3' },
      { url: 'https://picsum.photos/seed/mn2/620/440', alt: 'Mn 4' },
    ],
    photos: [{ _key: 'mn1', url: 'https://picsum.photos/seed/mn1/1200/800', alt: 'Installation 1' }],
    videos: [], audio: [], description: 'Documentation of a temporary public sculpture in Central Park.', links: [], order: 24,
  },
  {
    id: '25', slug: 'frequency', title: 'Frequency',
    subtitleType: 'By', subtitleName: 'Self-initiated',
    type: ['Film'], date: 'August 2022',
    thumbnail: { url: 'https://picsum.photos/seed/freq/620/440', alt: 'Frequency', width: 620, height: 440 },
    thumbnails: [
      { url: 'https://picsum.photos/seed/freq/620/440', alt: 'Fq 1' },
      { url: 'https://picsum.photos/seed/freq-b/620/440', alt: 'Fq 2' },
      { url: 'https://picsum.photos/seed/fq1/620/440', alt: 'Fq 3' },
    ],
    photos: [{ _key: 'fq1', url: 'https://picsum.photos/seed/fq1/1200/800', alt: 'Frame 1' }],
    videos: [{ _type: 'linkedVideo', _key: 'fqv1', url: 'https://vimeo.com/148751763', caption: 'Full film' }],
    audio: [], description: 'Experimental short about signal and noise.', links: [], order: 25,
  },
  {
    id: '26', slug: 'horizon', title: 'Horizon',
    subtitleType: 'For', subtitleName: 'Hermès', subtitleUrl: 'https://hermes.com',
    type: ['Campaign'], date: 'June 2023',
    thumbnail: { url: 'https://picsum.photos/seed/horizon/620/440', alt: 'Horizon', width: 620, height: 440 },
    thumbnails: [
      { url: 'https://picsum.photos/seed/horizon/620/440', alt: 'Hz 1' },
      { url: 'https://picsum.photos/seed/horizon-b/620/440', alt: 'Hz 2' },
      { url: 'https://picsum.photos/seed/hz1/620/440', alt: 'Hz 3' },
      { url: 'https://picsum.photos/seed/hz2/620/440', alt: 'Hz 4' },
    ],
    photos: [{ _key: 'hz1', url: 'https://picsum.photos/seed/hz1/1200/800', alt: 'Image 1' }],
    videos: [{ _type: 'linkedVideo', _key: 'hzv1', url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', caption: 'Brand film' }],
    audio: [], description: 'Campaign film and photography for Hermès.', links: [],
    roles: ['Creative Direction', 'Audiovisual Direction', 'Music Supervision'], order: 26,
  },
  {
    id: '27', slug: 'score', title: 'Score',
    subtitleType: 'By', subtitleName: 'Self-initiated',
    type: ['Performance', 'Releases'], date: 'September 2022',
    thumbnail: { url: 'https://picsum.photos/seed/score/620/440', alt: 'Score', width: 620, height: 440 },
    thumbnails: [
      { url: 'https://picsum.photos/seed/score/620/440', alt: 'Sc 1' },
      { url: 'https://picsum.photos/seed/score-b/620/440', alt: 'Sc 2' },
      { url: 'https://picsum.photos/seed/sc1/620/440', alt: 'Sc 3' },
    ],
    photos: [{ _key: 'sc1', url: 'https://picsum.photos/seed/sc1/1200/800', alt: 'Performance 1' }],
    videos: [], audio: [], description: 'A scored performance work across five acts.', links: [], order: 27,
  },
  {
    id: '28', slug: 'aperture', title: 'Aperture',
    subtitleType: 'For', subtitleName: 'Miu Miu',
    type: ['Fashion'], date: 'January 2023',
    thumbnail: { url: 'https://picsum.photos/seed/aperture/620/440', alt: 'Aperture', width: 620, height: 440 },
    thumbnails: [
      { url: 'https://picsum.photos/seed/aperture/620/440', alt: 'Ap 1' },
      { url: 'https://picsum.photos/seed/aperture-b/620/440', alt: 'Ap 2' },
      { url: 'https://picsum.photos/seed/ap1/620/440', alt: 'Ap 3' },
      { url: 'https://picsum.photos/seed/ap2/620/440', alt: 'Ap 4' },
    ],
    photos: [{ _key: 'ap1', url: 'https://picsum.photos/seed/ap1/900/1200', alt: 'Look 1' }],
    videos: [], audio: [], description: 'Campaign photography for Miu Miu.', links: [], order: 28,
  },
]

export const DUMMY_ABOUT: About = {
  photo: { url: 'https://picsum.photos/seed/phantom-about/600/800', alt: 'Phantom Projects portrait' },
  bio: 'Phantom Projects is an independent creative studio based in New York City. We make films, photographs, and experiences that sit at the intersection of fashion, culture, and art. Our work moves between commissioned projects and self-initiated research, always with a focus on the precise and the unexpected.',
  socials: [
    { label: 'Instagram', url: 'https://instagram.com' },
    { label: 'Vimeo', url: 'https://vimeo.com' },
  ],
}
